spring:
  datasource:
    url: jdbc:postgresql://192.168.10.94:54321/springgis
    username: gis
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    separator: //